Added taking/droping multiple files, colors, and container/test
Taking and drop file operations are unforutnately not symmetric
i.e. take file* works, but drop file* doesnt.
thanks bash

diff --git a/scripts/drop b/scripts/drop
--- a/scripts/drop
+++ b/scripts/drop
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+check_env() {
+  #if [[ -z $( env | grep "${1}") ]]; then
+  if ! env | grep -q "${1}" ; then
+    export -p ${1}="${2}"
+  fi
+}
+
+check_env "DROP_COLOR" "\e[93m"
+
+BLANK="\e[0m"
+
 if [ -z "$INVDIR" ]; then
   invdir=~/.inventory
 else
@@ -7,29 +18,43 @@ else
 fi
 
 if [ ! -d "$invdir" ]; then
-	echo ""$invdir" does not exist, creating..."
+	echo "$invdir does not exist, creating..."
   mkdir "$invdir"
 fi
 
-if [ ! -e "$invdir"/"$1" ]; then
-  echo "You can't drop something that doesn't exist!"
-else
-  if [ -e ./"$1" ]; then
-    printf "Oh no!\nThe file that you are trying to drop already exists. Please rename it or drop it somewhere else.\n"
-  else
-    mv "$invdir"/"$1" ./
-    echo "You dropped "$1"."
-  fi
-fi
+#This works for taking multiple files but globbing fails 
+# Putting in a function and passing file* as arg might make globbing work
+check_inv(){
 
-files=(""$invdir"/*")
-filesnum=$(ls -l "$invdir" | grep -v ^t | wc -l)
-
-if [ "$filesnum" -eq 0 ]; then
-  echo "Your inventory is empty."
-else
-  echo "Your inventory now contains:"
-  for i in ${files[@]}; do
-    echo "${i##*/}"
+  while [ $# -ne 0 ]; do
+    cur=${1}
+    # this changes with the find logic
+    # if [ ! -e "$invdir"/"$cur" ]; then
+    if [ ! -e "$invdir/$cur" ]; then
+      echo "You can't drop something that doesn't exist!"
+    else
+      if [ -e "./${cur##*/}" ]; then
+        printf "Oh no!\nThe file %s that you are trying to drop already exists. Please rename it or drop it somewhere else.\n" "$cur"
+      else
+        # this changes with the find logic
+        # echo -e "\e[38;5;201m${cur}${BLANK}"
+        mv -i "${invdir}/${cur}" ./
+        echo -e "You dropped ${DROP_COLOR}$cur${BLANK}."
+      fi
+    fi
+    shift
   done
-fi
+}
+
+# ok the * needs to escaped on the command line (i.e. drop .hidden\*)
+# drop_list=$(find "${invdir}" -name "$*" )
+
+#drop_list=$(find "${invdir}" -name "$@" )
+#drop_list=$(ls "${invdir}/$*" )
+#echo $drop_list
+
+check_inv $@
+
+inventory
+
+# vim: ts=2 sw=2 expandtab
diff --git a/scripts/take b/scripts/take
--- a/scripts/take
+++ b/scripts/take
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+
+check_env() {
+  #if [[ -z $( env | grep "${1}") ]]; then
+  if ! env | grep -q "${1}" ; then
+    export -p ${1}="${2}"
+  fi
+}
+
+# [[ -n $NOCOLOR ]] && export -p TAKE_COLOR="[0m"
+#check_env "INVENTORY_COLOR" "\e[95m"
+
+check_env "TAKE_ERR_COLOR" "[91m"
+check_env "TAKE_COLOR" "[93m"
+
+BLANK="\e[0m"
+
 if [ -z "$INVDIR" ]; then
   invdir=~/.inventory
 else
@@ -7,29 +23,25 @@ else
 fi
 
 if [ ! -d "$invdir" ]; then
-	echo ""$invdir" does not exist, creating..."
+	echo "$invdir does not exist, creating..."
   mkdir "$invdir"
 fi
 
-if [ ! -e "$1" ]; then
-  echo "You can't take something that doesn't exist!"
-else
-  if [ -e "$invdir"/"$1" ]; then
-    printf "Oh no!\nThe file that you are trying to take already exists in your inventory. Please rename it.\n"
+while [ $# -ne 0 ]; do
+  cur=${1}
+  if [ ! -e "$cur" ]; then
+    echo "You can't take something that doesn't exist!"
   else
-    mv ./"$1" "$invdir"
-    echo "You took "$1"."
+    if [ -e "$invdir"/"$cur" ]; then
+      printf "Oh no!\nThe file \e%s%s\e[0m that you are trying to take already exists in your inventory. Please rename it.\n" "${TAKE_ERR_COLOR}" "$cur "
+    else
+      mv -i ./"$cur" "$invdir"
+      printf "You took \e%s%s\e[0m\n" "${TAKE_COLOR}" "$cur"
+    fi
   fi
-fi
+	shift
+done
 
-files=(""$invdir"/*")
-filesnum=$(ls -l "$invdir" | grep -v ^t | wc -l)
+inventory
 
-if [ "$filesnum" -eq 0 ]; then
-  echo "Your inventory is empty."
-else
-  echo "Your inventory now contains:"
-  for i in ${files[@]}; do
-    echo "${i##*/}"
-  done
-fi
+# vim: ts=2 sw=2 expandtab
